config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  post "msg", to: "welcome#message", as: :yourmsg
  root to: "welcome#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  protect_from_forgery except: [:message]
  def index
  end
  def message
    @message=Message.new(msg_params)
    @message.save
  end
  private
  def msg_params
    params.permit(:nom,:email,:sujet,:typeq,:monmessage)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    <title>ok dac bazar - kourou</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/album/">

    

    

<link href="https://getbootstrap.com/docs/5.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="https://getbootstrap.com/docs/5.2/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="<%=asset_path "logoicon"%>" sizes="32x32" type="image/png">
<link rel="icon" href="<%=asset_path "logoicon"%>" sizes="16x16" type="image/png">
<link rel="manifest" href="https://getbootstrap.com/docs/5.2/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="https://getbootstrap.com/docs/5.2/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="<%=asset_path "logoicon"%>">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
  </head>
  <body>
    
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">BAZAR OK DAC, 9027 RUE ALFRED DREYFUS 97310 KOUROU</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Suis moi sur Twitter</a></li>
            <li><a href="#" class="text-white">Like sur Facebook</a></li>
            <li><a href="#" class="text-white">Envoie moi un email</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="/" class="navbar-brand d-flex align-items-center">
        <strong>Accueil</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<%=yield%>
<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Revenir en haut</a>
    </p>
    <p class="mb-1">Contacte le vendeur !</p>
    <p class="mb-0">Nouveau chez ok dac ? envoyez un message.</p>
  </div>
</footer>


    <script src="https://getbootstrap.com/docs/5.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    <script>
      <%=yield :script%>
      </script>
  </body>
</html>

app/views/welcome/index.html.erb
<%=content_for :script do%>
<%end%>
<main>
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel" >
  <div class="carousel-inner">
      <%notfirst=false%>
      <%(1..5).to_a.map {|x|"accueil#{x}.JPG"}.each do |y|%>
      
    <div class="carousel-item <%=!notfirst ? "active" : ""%>">
      <%=image_tag y, {style:"height:400px;", class: "d-block w-100"}%>
    </div>
      <%notfirst = true%>
    <%end%>
  </div>
</div>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Ok dac bazar</h1>
        <p class="lead text-muted">Bricolage - électricité - jardinage - outillage - plomberie - quincaillerie</p>
        <p>
          <a href="#achat" class="btn btn-primary my-2">Contacter le vendeur pour un achat</a>
          <a href="#achat" onclick="typeq.value=0;" class="btn btn-secondary my-2">Contacter le vendeur pour toute autre question</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <%=image_tag "accueil1.JPG",{class:"card-img-top", width: "100%", height: "225"}%>

            <div class="card-body">
              <p class="card-text">OUVERT DU LUNDI AU SAMEDI</p>
              <p class="card-text">8h30 - 13h00</p>
              <p class="card-text">16h00 - 19h00</p>
              
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
              <%=image_tag "accueil3.JPG",{class:"card-img-top", width: "100%", height: "225"}%>
            <div class="card-body">
              <p class="card-text">Vente de Quincaillerie </p>
              <p class="card-text">Vente de produits de décoration - électricité - jardinage - outillage - plomberie</p>
              
            </div>
          </div>
        </div>
      </div></div></div>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
       <form action="/" method="post" id="achat" onclick="$.ajax({type:'post',url: '<%=yourmsg_path%>?'+$(achat).serialize(), success: function(data){envoimsg.innerHTML='Votre message a été envoyé.';}, error: function(){envoimsg.innerHTML='Il y a eu une erreur lors de l\'envoi.';} });return false;">
  <fieldset>
    <legend>Ok dac ! contactez moi !</legend>
     <div class="mb-3">
      <label for="nom" class="form-label">Votre nom</label>
      <input type="text" name="nom" required id="nom" style="" class="form-control" placeholder=""/>
    </div>
     <div class="mb-3">
      <label for="email" class="form-label">Votre email</label>
      <input type="email" name="email" required id="email" style="" class="form-control" placeholder=""/>
    </div>
    <div class="mb-3">
      <label for="typeq" class="form-label">au sujet de </label>
      <select name="typeq" id="typeq" class="form-select">
        <option value="1">quincaillerie</option>
        <option value="2">électricité</option>
        <option value="3">jardinage</option>
        <option id="question" value="0">autre question</option>
      </select>
    </div>
 <div class="mb-3">
      <label for="monmessage" class="form-label">Votre message</label>
      <textarea name="monmessage" required id="monmessage" style="height: 100px;" class="form-control" placeholder=""></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </fieldset>
</form>
          <p id="envoimsg"></p>
      </div>
    </div>
  </section>

</main>